baseURL = ""
title = "Website Name"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
themesDir = "themes"
publishDir = "public"

[params]
description = "Your site description"
copyright = "Copyright © 2021 Your Name"
dark = "auto"
highlight = true

[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 20

[permalinks]
posts = "/:title/"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true
